# Generated by Django 5.0 on 2025-05-05 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="phone_number",
            field=models.CharField(max_length=45, verbose_name="شماره تلفن"),
        ),
    ]
