# Generated by Django 5.0 on 2025-05-05 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0002_alter_customer_phone_number"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="invoice",
            options={"verbose_name": "فاکتور", "verbose_name_plural": "فاکتور"},
        ),
    ]
